apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello5
  template:
    metadata:
      labels:
        app: hello5
    spec:
      containers:
      - name: hello5
        image: ${IMAGE_HOST}/hello5:1.0.0.2
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: COREFX_DEPLOY_NAME
          value: hello5
        - name: COREFX_API_NAME
          value: hello5-dev
        - name: HELLO_HELLODB_CONN
          value: ${HELLO_HELLODB_CONN}
        - name: HELLO_REDIS_CACHE_CONN
          value: ${HELLO_REDIS_CACHE_CONN}