apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello8-api-dev-ingress
spec:
  rules:
  - http:
      paths:
      - path: /hello8/?(.*)
        backend:
          serviceName: hello8-api-dev-svc
          servicePort: 80